Refactor code
BenMukebo/school-library pull request #5
Opened 2021-12-20 15:03 UTC by BenMukebo

## In this Milestone, we use the newly acquired knowledge and refactor the previous code.

- Make sure YAGNI, KISS, and DRY rules and Ruby style guide are respected.
- Follow SOLID principles.
- Pay special attention to the "Single-responsiblity Principle".
   - Make sure that the role of main.rb is only to start your code and ask the user for the initial choice of options (or to quit).
   - Extract some pieces of logic into separate class(es).

2021-12-20 15:16 UTC, mikethreels requested changes
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-20 15:16 UTC, mikethreels commented on app.rb
> +  end
- [ ] great job cleaning up the main.rb file 👍 in this method text is printed, information is gathered and processed, this is not according to the single responsibility principle. try to split this into smaller easier to maintain methods. have a look at [this article](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/lessons/solid.md#best-practices-and-solid) for more information.

2021-12-20 15:16 UTC, mikethreels commented on app.rb
> +  end
- [ ] great job cleaning up the main.rb file 👍 in this method text is printed, information is gathered and processed, this is not according to the single responsibility principle. try to split this into smaller easier to maintain methods. have a look at [this article](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/lessons/solid.md#best-practices-and-solid) for more information.

2021-12-20 15:16 UTC, mikethreels commented on app.rb
> +  end
- [ ] great job cleaning up the main.rb file 👍 in this method text is printed, information is gathered and processed, this is not according to the single responsibility principle. try to split this into smaller easier to maintain methods. have a look at [this article](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/lessons/solid.md#best-practices-and-solid) for more information.

2021-12-21 08:19 UTC, TedLivist approved these changes
## STATUS: APPROVED ✔️ ✔️

Hi @BenMukebo and @mmsesay,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-21 08:24 UTC, merged